import { supabase } from "./supabase"

// Puedes agregar nuevos inmuebles directamente a este array
// Mantén el orden alfabético para facilitar la búsqueda
export const INMUEBLES = [
  "Accesos",
  "Baños",
  "Biosaludables",
  "Calistenia",
  "Camerinos",
  "Cancha De Baloncesto",
  "Cancha De Tenis",
  "Cancha De Voley Playa",
  "Cancha Fútbol",
  "Cancha Múltiple",
  "Cancha Sintética",
  "Cerramiento",
  "Coliseo",
  "Edificación",
  "Encerramiento",
  "Gimnasio",
  "Gradería (Metálica/Concreto)",
  "Huerta",
  "Juegos Infantiles",
  "Juegos Primera Infancia",
  "Pantallas De Protección",
  "Piscina Niños",
  "Piscinas Adultos",
  "Pista De Patinaje",
  "Pista De Trote",
  "Salón Múltiple - Kiosko",
  "Vestier",
].filter((item) => item && item.trim() !== "") // Esto eliminará cualquier valor vacío o solo espacios

export const MUEBLES = [
  "Bomba",
  "Canecas De Basura",
  "Computadores",
  "Escritorios",
  "Guadaña",
  "Manguera",
  "Motores De Piscina",
  "Otras Sillas",
  "Podadora",
  "Pozo",
  "Sillas Rimax",
]

export const COMUNAS = [
  "Comuna 1",
  "Comuna 2",
  "Comuna 3",
  "Comuna 4",
  "Comuna 5",
  "Comuna 6",
  "Comuna 7",
  "Comuna 8",
  "Comuna 9",
  "Comuna 10",
  "Comuna 11",
  "Comuna 12",
  "Comuna 13",
  "Comuna 14",
  "Comuna 15",
  "Comuna 16",
  "Comuna 17",
  "Comuna 18",
  "Comuna 19",
  "Comuna 20",
  "Comuna 21",
  "Comuna 22",
  "Corregimiento Montebello",
]

export const BARRIOS = [
 "Aguablanca",
"Alto Aguacatal",
"Antonio Nariño",
"Bajos De Ciudad Córdoba",
"Brisas Del Limonar",
"Ciudad 2000",
"Ciudad Córdoba Sector 1A-1B",
"Ciudad Córdoba Sector 3",
"Ciudad Córdoba Sector 3A-3B",
"Ciudad Modelo",
"Colseguros",
"Conquistadores",
"Cristóbal Colón",
"Departamental",
"Descubrimiento",
"Eldorado I",
"Eldorado II",
"El Guabal",
"El Jardín",
"El Retiro",
"El Saladito",
"El Vallado I",
"El Vallado II",
"Felidia",
"Fortaleza",
"Jorge Zawadsky",
"José Holguín Garcés",
"José María Córdoba",
"La 23",
"La Castilla",
"La Esperanza",
"La Gran Colombia",
"La Independencia",
"La Portada",
"La Selva",
"Las Acacias",
"Laureano Gómez",
"Llano Verde",
"Mariano Ramos",
"Marino Rengifo",
"Mojica II",
"Montebello",
"Morichal I",
"Morichal II",
"Morichal III",
"Morichal IV",
"Nacional",
"Olímpico",
"Panamericano",
"Pasoancho",
"Prados De Oriente",
"Primavera",
"República De Israel",
"Reservados De Córdoba",
"San Benito",
"San Carlos",
"San Cristóbal",
"San Judas I",
"San Judas Tadeo I",
"San Judas Tadeo II",
"San Juan Bautista",
"San Pedro Caver",
"Santa Clara",
"Santa Elena",
"Sport Boys",
"Terrón Colorado",
"Unión De Vivienda Popular",
"Urbanización Aguacatal",
"Urbanización La Fortuna",
"Villa Del Mar",
"Villa Del Sur",
"Villaepal",
"Villacarmelo",
"Vista Hermosa",
  "Alameda",
"Alférez Real",
"Alto Jordán",
"Alto Nápoles",
"Alto Polvorines",
"Altos De Santa Helena",
"Arboleda",
"Bajo Polvorines",
"Belalcázar",
"Belén",
"Belisario Caicedo",
"Bellavista",
"Bloques Del Limonar",
"Bosques Del Limonar",
"Bretaña",
"Brisas De Mayo",
"Buenos Aires",
"Caldas",
"Calipso I",
"Calipso Ii",
"Calipso Iii",
"Cambulos",
"Camino Real",
"Caney Especial",
"Cañaverales",
"Cañaverales 3",
"Cañaveralejo",
"Cascada",
"Carlos Lleras Restrepo",
"Charco Azul",
"Ciudad Capri",
"Ciudadela Comfandi",
"Ciudadela De Comfandi",
"Colinas Del Sur",
"Comuneros Ii",
"Corregimiento El Hormiguero",
"Cuarto De Legua",
"El Caney",
"El Diamante",
"El Ingenio",
"El Limonar",
"El Poblado I",
"El Poblado Ii",
"Escobar Navia",
"Farallones",
"Francisco Eladio Ramírez",
"Gran Limonar Cataya",
"Joaquín Borrero Sinisterra",
"Junín",
"La Cascada",
"La Estrella-Siloe",
"La Hacienda",
"La Paz",
"La Playa",
"Lagos I",
"Laguito",
"Lleras Camargo",
"Los Chorros",
"Los Robles",
"Lourdes",
"Manuel María Benaventura",
"Mandarinos",
"Marroquín Iii",
"Mayapán",
"Meléndez",
"Mortiñal",
"Nápoles",
"Niza",
"Nueva Tequendama",
"Nuevo Horizonte",
"Nuevo Rey (Santa Paula)",
"Obrero",
"Pance",
"Pance Cabecera",
"Parcelaciones Pance",
"Poblado I",
"Poblado Ii",
"Pondaje",
"Prados Del Limonar",
"Prados Del Sur",
"Primero De Mayo",
"Refugio",
"Ricardo Balcázar",
"Ricardo Balcázar Ii",
"Robles",
"Rodrigo Lara Bonilla",
"Samanes De Guadalupe",
"Santa Ana",
"Tequendama",
"Ulpiano Lloreda",
"Urbanización San Joaquín",
"Valle Del Lili",
"Venezuela",
"Vereda Los Andes",
"Villa Blanca",
"Villa Del Lago",
"Villas De Guadalupe",
"Yira Castro",
]

export const ESCENARIOS_DEPORTIVOS = [
"Cancha Baloncesto La Colmena El Vallado I",
"Cancha De Baloncesto San Carlos",
"Cancha De Fútbol 5 San Carlos",
"Cancha De Fútbol El Retiro",
"Cancha De Fútbol Felidia",
"Cancha De Fútbol Llano Verde La Paz",
"Cancha De Fútbol Montebello",
"Cancha De Fútbol Montebello Mojica II Visa",
"Cancha De Fútbol Primavera",
"Cancha Fútbol 11 Villa Del Sur",
"Cancha Múltiple África El Retiro",
"Cancha Múltiple Barrio El Guabal",
"Cancha Múltiple Barrio El Retiro",
"Cancha Múltiple Ciudad Modelo",
"Cancha Múltiple Comuneros I (Alfonso Bonilla Naar)",
"Cancha Múltiple Comuneros I (El Faro)",
"Cancha Múltiple De Vista Hermosa",
"Cancha Múltiple Del Mico San Carlos",
"Cancha Múltiple El Árbol Llano Verde",
"Cancha Múltiple El Jardín",
"Cancha Múltiple El Jardín Autoservicio",
"Cancha Múltiple El Triángulo Barrio Mariano Ramos",
"Cancha Múltiple Guadalajara El Vallado II",
"Cancha Múltiple Holguín Garcés",
"Cancha Múltiple José María Córdoba",
"Cancha Múltiple La Castilla",
"Cancha Múltiple La Fortuna",
"Cancha Múltiple La Playita",
"Cancha Múltiple Las Acacias",
"Cancha Múltiple Llano Verde",
"Cancha Múltiple Los Cristales",
"Cancha Múltiple Montebello",
"Cancha Múltiple Nacional",
"Cancha Múltiple Reservados De Córdoba",
"Cancha Múltiple San Judas I",
"Cancha Múltiple Secon Barrio El Retiro",
"Cancha Múltiple Suley El Vallado I",
"Cancha Múltiple Urbanización Aguacatal",
"Cancha Múltiple Villa Del Mar",
"Cancha Múltiple Villa Del Sur",
"Cancha Sintética 1 Bajo Ciudad Córdoba",
"Cancha Sintética 2 Bajo Ciudad Córdoba",
"Cancha Sintética Brisas Del Limonar",
"Cancha Sintética República De Israel",
"Cancha Sintética San Benito",
"Coliseo Celestino Mutis",
"Coliseo Cubierto Bajo Aguacatal",
"Kiosco 3 Edad Luis H. Garces",
"Kiosco 3º Edad Cent Mult Rocio La Selva",
"Kiosco De La 3º Edad Anhelos De Vivir",
"Kiosco Manantial Del Guabal",
"Kiosco Mañanitas Del Guabal",
"Kiosco Morichal II",
"Kiosco Reservados De Ciudad Córdoba",
"Parque Del Amor Llano Verde",
"Parque Infantil Fortaleza",
"Parque Recreativo 20 De Julio",
"Parque Recreativo Aguablanca",
"Parque Recreativo Antonio Nariño",
"Parque Recreativo Barrio Olímpico",
"Parque Recreativo Barrio Villaepal",
"Parque Recreativo Brisas Del Limonar",
"Parque Recreativo Canchas Gemelas Mojica II Visa A",
"Parque Recreativo Colseguros Andes",
"Parque Recreativo Comuneros I",
"Parque Recreativo Cousaca",
"Parque Recreativo Departamental",
"Parque Recreativo El Ancla",
"Parque Recreativo El Guabal",
"Parque Recreativo El Jardín",
"Parque Recreativo El Pascualito Comuneros I (Parque Del Muerto)",
"Parque Recreativo El Pascualito El Vallado II",
"Parque Recreativo El Recuerdo",
"Parque Recreativo Jorge Zawadsky",
"Parque Recreativo La Alhambra",
"Parque Recreativo La Amistad El Vallado II",
"Parque Recreativo La Bombonera Mojica II",
"Parque Recreativo La India Barrio Santa Elena",
"Parque Recreativo La Independencia",
"Parque Recreativo La Virgen Mariano Ramos",
"Parque Recreativo Las Palmas",
"Parque Recreativo Los Bomberos El Vallado II",
"Parque Recreativo Mojica II",
"Parque Recreativo Morichal I",
"Parque Recreativo Morichal II",
"Parque Recreativo Morichal III",
"Parque Recreativo Morichal IV",
"Parque Recreativo Panamericano",
"Parque Recreativo Primavera",
"Parque Recreativo República De Israel",
"Parque Recreativo San Benito",
"Parque Recreativo San Judas Tadeo I",
"Parque Recreativo Santa Clara",
"Parque Recreativo Y Kiosco Bajos Ciudad Córdoba",
"Parque Tertualiadero 3 Edad San Carlos",
"Polideportivo Barrio El Vallado",
"Polideportivo Canchas Gemelas Mojica II Visa A",
"Polideportivo Ciudad 2000",
"Polideportivo Ciudad Córdoba Sec 3A Y 3B",
"Polideportivo Ciudad Córdoba Sector 1A",
"Polideportivo Ciudad Córdoba Sector 3",
"Polideportivo Comuneros I",
"Polideportivo Conquistadores",
"Polideportivo Cristo Maestro Barrio Unión De Vivienda Popular",
"Polideportivo Cristóbal Colón",
"Polideportivo Eduardo Vargas (El Vallado)",
"Polideportivo Eldorado I",
"Polideportivo Eldorado II",
"Polideportivo El Jardín",
"Polideportivo Jorge Zawadsky",
"Polideportivo La 23",
"Polideportivo La Bombonera",
"Polideportivo La Esperanza",
"Polideportivo La Gran Colombia",
"Polideportivo La Selva",
"Polideportivo Las Malvinas",
"Polideportivo Prados De Oriente",
"Polideportivo República De Israel",
"Polideportivo San Carlos Cancha Santiago Apóstol",
"Polideportivo San Cristóbal",
"Polideportivo San Judas Tadeo II",
"Polideportivo San Juan Bautista",
"Polideportivo San Pedro",
"Polideportivo Sport Boys Barrio Mariano Ramos",
"Polideportivo Unión De Vivienda Popular (Parque De Los Colores)",
"Polideportivo Villacarmelo",
"Tertuliadero Villa Del Sur",
"Unidad Recreativa Ciudad Modelo (CRP)",
"Unidad Recreativa Descubrimiento",
"Unidad Recreativa El Guabal",
"Unidad Recreativa El Olímpico",
"Unidad Recreativa El Vallado",
"Unidad Recreativa Laureano Gómez",
"Unidad Recreativa Los Castores",
"Unidad Recreativa Los Cristales",
"Unidad Recreativa Mariano Ramos",
"Unidad Recreativa Marino Rengifo",
"Unidad Recreativa Panamericano",
"Unidad Recreativa Tory Castro (CRP)",
"Unidad Recreativa Villa Del Sur (CRP)",
  "Biosaludables Charco Azul",
"Cancha Brisas De La Chorrera",
"Cancha De Baloncesto Calipso 3",
"Cancha De Baloncesto El Caney Especial",
"Cancha De Baloncesto La Cascada",
"Cancha De Baloncesto Servivienda Bajo Polvorines",
"Cancha De Baloncesto Valle Del Lili",
"Cancha De Fútbol 5 Robles",
"Cancha De Fútbol Barrio El Caney",
"Cancha De Fútbol Charco Azul",
"Cancha De Fútbol Fe Y Alegría La Pedregosa",
"Cancha De Fútbol Gran Limonar Cataya",
"Cancha De Fútbol La Cero Comuneros 2",
"Cancha De Fútbol Maracaná",
"Cancha De Fútbol Nuevo Rey (Santa Paula)",
"Cancha De Fútbol Polvo Rojo Alto Nápoles",
"Cancha De Fútbol Prados Del Limonar",
"Cancha De Fútbol Villa Blanca",
"Cancha De Futsala Pampas Del Mirador",
"Cancha El Mortiñal",
"Cancha El Pascualito",
"Cancha La 30",
"Cancha Múltiple Alto Colinas",
"Cancha Múltiple Bellavista",
"Cancha Múltiple Buenos Aires",
"Cancha Múltiple Charco Azul Feria",
"Cancha Múltiple Charco Azul Sardi",
"Cancha Múltiple Comedores",
"Cancha Múltiple Comuneros 2",
"Cancha Múltiple Comuneros La Fulin 2",
"Cancha Múltiple El Limonar",
"Cancha Múltiple La Amistad",
"Cancha Múltiple La Arboleda",
"Cancha Múltiple La Siri",
"Cancha Múltiple La Unik Poblado 1",
"Cancha Múltiple Loma Linda Alto Jordán",
"Cancha Múltiple Longitudinal Poblado 2 Sector Patinaje",
"Cancha Múltiple Longitudinal Poblado 2 Sector Sena",
"Cancha Múltiple Los Lagos 1",
"Cancha Múltiple Los Robles",
"Cancha Múltiple Los Robles Quimbaya",
"Cancha Múltiple Nuevo Horizonte",
"Cancha Múltiple Piñuelas Alto Meléndez",
"Cancha Múltiple Poblado 2",
"Cancha Múltiple Ricardo Balcázar",
"Cancha Múltiple Yira Castro",
"Cancha Salón Azul",
"Cancha Sintética Calipso 3",
"Cancha Sintética Junín",
"Cancha Sintética Las Gemelas Poblado 1",
"Canchas De Cañaveralejo",
"Canchas Del Venezuela",
"Canchas Múltiple Belén",
"Canchas Urbanización Venezuela",
"Centro Múltiple Comuneros 2",
"Centro Múltiple La Cascada",
"Escenario Deportivo Y Recreativo Alférez Real",
"Kiosco Adulto Mayor Bosques Del Limonar (Flores De Mayo)",
"Kiosco Bloques Del Limonar (Centro Múltiple)",
"Kiosco Tercera Edad Ciudad Capri",
"Kiosco Tertuliadero Ricardo Balcázar",
"La Carolina",
"Parque Alférez Real",
"Parque De Belisario",
"Parque El Borracho",
"Parque El Caney Iv",
"Parque El Trébol",
"Parque El Triángulo",
"Parque Infantil Barrio Caldas",
"Parque La Virgen",
"Parque Lineal Camino Real",
"Parque Recreativo Alférez Real 1",
"Parque Recreativo Alférez Real 2 (Las Mercedes)",
"Parque Recreativo Altos Del Caney",
"Parque Recreativo Arboleda",
"Parque Recreativo Bloques Del Limonar",
"Parque Recreativo Bosques Del Limonar La Hormiga",
"Parque Recreativo Buenos Aires",
"Parque Recreativo Calipso 1",
"Parque Recreativo Calipso 2",
"Parque Recreativo Cambulos",
"Parque Recreativo Cañaverales 3",
"Parque Recreativo Ciudad Capri",
"Parque Recreativo Ciudadela Comfandi",
"Parque Recreativo Comfandi Los Enanos",
"Parque Recreativo Cuarto De Legua",
"Parque Recreativo Divino Salvador",
"Parque Recreativo El Laguito",
"Parque Recreativo El Limonar",
"Parque Recreativo El Poblado 2",
"Parque Recreativo El Pondaje",
"Parque Recreativo Escobar Navia Lourdes",
"Parque Recreativo Farallones",
"Parque Recreativo Javier Aba",
"Parque Recreativo Joaquín Borrero",
"Parque Recreativo La Arboleda",
"Parque Recreativo La Cascada",
"Parque Recreativo La Guitarra",
"Parque Recreativo La Hacienda",
"Parque Recreativo La Hormiga Comuneros 2",
"Parque Recreativo Lara Bonilla",
"Parque Recreativo Los Mandarinos",
"Parque Recreativo Lourdes",
"Parque Recreativo Marroquín 3",
"Parque Recreativo Mayapán",
"Parque Recreativo Niza",
"Parque Recreativo Pampalinda",
"Parque Recreativo Prados Del Sur",
"Parque Recreativo Refugio",
"Parque Recreativo Samanes De Guadalupe",
"Parque Recreativo Santa Ana",
"Parque Recreativo Santa Anita (Colombo Amer)",
"Parque Recreativo Santa Helena",
"Parque Recreativo Seguros Patria",
"Parque Recreativo Ulpiano Lloreda",
"Parque Recreativo Urbanización Nápoles",
"Parque Recreativo Villa Campestre Del Río Ii",
"Parque Recreativo Villa Del Lago",
"Parque Recreativo Villas De Guadalupe",
"Parque San Joaquín",
"Pista De Patinaje Alto Jordán",
"Plazoleta Alameda",
"Plazoleta Frente A La Iglesia Santisima Trinidad",
"Polideportivo Carlos Lleras Restrepo",
"Polideportivo Cañaverales 6",
"Polideportivo Colinas Del Sur",
"Polideportivo El Banqueo",
"Polideportivo El Crucero",
"Polideportivo El Hormiguero",
"Polideportivo El Plan",
"Polideportivo El Rosario",
"Polideportivo Francisco Eladio Ramírez",
"Polideportivo La Cascada",
"Polideportivo La Horqueta",
"Polideportivo La Paz",
"Polideportivo La Playa",
"Polideportivo Los Fundadores",
"Polideportivo Obrero",
"Polideportivo Pance Cabecera",
"Polideportivo Poblado 1",
"Polideportivo Primero De Mayo",
"Polideportivo Ricardo Balcázar",
"Polideportivo Ricardo Balcázar 2",
"Polideportivo Tequendama",
"Polideportivo Ulpiano Lloreda",
"Polideportivo Valle Del Lili",
"Unidad Recreativa Cañaveralejo",
"Unidad Recreativa Cañaverales",
"Unidad Recreativa Ciudadela De Comfandi (CRP)",
"Unidad Recreativa El Diamante (CRP)",
"Unidad Recreativa Horizontes",
"Unidad Recreativa La Estrella",
"Unidad Recreativa Lourdes",
"Unidad Recreativa Primero De Mayo",
"Unidad Recreativa Quintas Del Refugio",
"Unidad Recreativa Santiago De Cali",
"Unidad Recreativa Villa Del Lago",
"Zona Verde Atabanza",
"Zona Verde Ciudadela Del Río",
  
]

export async function getItemsDisponibles(seccion: string) {
  try {
    // Primero intentamos obtener los items personalizados
    const { data: customItems, error } = await supabase
      .from("items_disponibles")
      .select("nombre")
      .eq("seccion", seccion)

    if (error) {
      console.error("Error al obtener items personalizados:", error)
      throw error
    }

    const customItemNames = customItems?.map((item) => item.nombre).filter(Boolean) || []
    const predefinedItems = seccion === "Inmuebles" ? INMUEBLES : MUEBLES

    // Combinar items predefinidos con items personalizados, eliminando duplicados y valores vacíos
    const combinedItems = Array.from(new Set([...predefinedItems, ...customItemNames])).filter(
      (item) => item && item.trim() !== "",
    )

    // Ordenar alfabéticamente
    return combinedItems.sort()
  } catch (error) {
    console.error("Error en getItemsDisponibles:", error)
    // En caso de error, devolver al menos los items predefinidos
    return (seccion === "Inmuebles" ? INMUEBLES : MUEBLES).filter((item) => item && item.trim() !== "")
  }
}

