import { supabase } from "./supabase"

// Puedes agregar nuevos inmuebles directamente a este array
// Mantén el orden alfabético para facilitar la búsqueda
export const INMUEBLES = [
  "Accesos",
"Accesibilidad PMR",
"Baños",
"Biosaludables",
"Calistenia",
"Camerinos",
"Cancha De Baloncesto",
"Cancha De Tenis",
"Cancha De Voley Playa",
"Cancha Fútbol",
"Cancha Múltiple",
"Cancha Sintética",
"Cerramiento",
"Coliseo",
"Edificación",
"Encerramiento",
"Gimnasio",
"Gradería (Metálica/Concreto)",
"Huerta",
"Juegos Infantiles",
"Juegos Primera Infancia",
"Pantallas De Protección",
"Piscina Niños",
"Piscinas Adultos",
"Pista De Patinaje",
"Pista De Trote",
"Pista De Parkour",
"Pista De Skate",
"Pista De BMX",
"Salón Múltiple - Kiosko",
"Vestier",
"Bodegas",
"Pozo",
"Motores De Piscina",
  // Para agregar un nuevo inmueble, simplemente añade una nueva línea aquí
  // siguiendo el formato: "Nombre Del Inmueble",
]

export const MUEBLES = [
  "Bomba",
"Canecas De Basura",
"Computadores",
"Escritorios",
"Guadaña",
"Manguera",
"Podadora",
"Sillas Rimax",
"Otras Sillas",
]

export const COMUNAS = [
  "Comuna 1",
  "Comuna 2",
  "Comuna 3",
  "Comuna 4",
  "Comuna 5",
  "Comuna 6",
  "Comuna 7",
  "Comuna 8",
  "Comuna 9",
  "Comuna 10",
  "Comuna 11",
  "Comuna 12",
  "Comuna 13",
  "Comuna 14",
  "Comuna 15",
  "Comuna 16",
  "Comuna 17",
  "Comuna 18",
  "Comuna 19",
  "Comuna 20",
  "Comuna 21",
  "Comuna 22",
  "Corregimiento Montebello",
]

export const BARRIOS = [
  "El Guabal",
  "San Judas I",
  "Pasoancho",
  "Departamental",
  "Fortaleza",
  "Conquistadores",
  "La Gran Colombia",
  "San Pedro Caver",
  "Villa Del Sur",
  "Aguablanca",
  "La Selva",
  "Villaepal",
  "Jorge Zawadsky",
  "Panamericano",
  "San Judas Tadeo I",
  "San Juan Bautista",
  "Llano Verde",
  "Reservados De Córdoba",
  "Morichal II",
  "Morichal I",
  "Morichal III",
  "Morichal IV",
  "Ciudad Córdoba Sector 3A-3B",
  "Ciudad Córdoba Sector 3",
  "Ciudad Córdoba Sector 1A-1B",
  "Nacional",
  "Vista Hermosa",
  "Urbanización La Fortuna",
  "Alto Aguacatal",
  "Urbanización Aguacatal",
  "Villa Del Mar",
  "Terrón Colorado",
  "Bajo Aguacatal",
  "La Portada",
  "Montebello",
  "El Saladito",
  "Felidia",
  "San Carlos",
  "Ciudad Modelo",
  "El Jardín",
  "La Independencia",
  "San Benito",
  "Prados De Oriente",
  "La Castilla",
  "Villacarmelo",
  "Las Acacias",
  "Santa Elena",
  "Olímpico",
  "Colseguros",
  "Santa Clara",
  "Cristóbal Colón",
  "Eldorado I",
  "Eldorado II",
  "La 23",
  "San Cristóbal",
  "San Judas Tadeo II",
  "Descubrimiento",
  "Primavera",
  "José Holguín Garcés",
  "José María Córdoba",
  "La Esperanza",
  "El Recuerdo",
  "Mojica II",
  "Comuneros I",
  "Bajos De Ciudad Córdoba",
  "Laureano Gómez",
  "Brisas Del Limonar",
  "Mariano Ramos",
  "República De Israel",
  "Antonio Nariño",
  "Ciudad 2000",
  "Unión De Vivienda Popular",
  "Sport Boys",
  "Marino Rengifo",
  "El Vallado I",
  "El Retiro",
  "El Vallado II",
]

export const ESCENARIOS_DEPORTIVOS = [
  "Cancha Múltiple Barrio El Guabal",
  "Cancha Múltiple San Judas I",
  "Parque Recreativo El Guabal",
  "Parque Recreativo La Alhambra",
  "Polideportivo Pasoancho",
  "Unidad Recreativa Los Castores",
  "Parque Infantil Fortaleza",
  "Polideportivo Conquistadores",
  "Polideportivo La Gran Colombia",
  "Polideportivo San Pedro",
  "Unidad Recreativa Villa Del Sur (Crp)",
  "Kiosco 3 Edad Luis H. Garces",
  "Parque Recreativo Aguablanca",
  "Kiosco 3º Edad Cent Mult Rocio La Selva",
  "Kiosco De La 3º Edad Anhelos De Vivir",
  "Kiosco Manantial Del Guabal",
  "Kiosco Mañanitas Del Guabal",
  "Parque Recreativo Barrio Villaepal",
  "Parque Recreativo Departamental",
  "Parque Recreativo Jorge Zawadsky",
  "Parque Recreativo Panamericano",
  "Parque Recreativo San Judas Tadeo I",
  "Polideportivo Jorge Zawadsky",
  "Polideportivo La Selva",
  "Polideportivo San Juan Bautista",
  "Unidad Recreativa El Guabal",
  "Unidad Recreativa Panamericano",
  "Cancha De Fútbol Llano Verde La Paz",
  "Cancha Múltiple El Árbol Llano Verde",
  "Cancha Múltiple Llano Verde",
  "Cancha Múltiple Reservados De Córdoba",
  "Kiosco Morichal II",
  "Kiosco Reservados De Ciudad Córdoba",
  "Parque Del Amor Llano Verde",
  "Parque Recreativo Morichal I",
  "Parque Recreativo Morichal II",
  "Parque Recreativo Morichal III",
  "Parque Recreativo Morichal IV",
  "Polideportivo Ciudad Córdoba Sec 3A Y 3B",
  "Polideportivo Ciudad Córdoba Sector 3",
  "Polideportivo Ciudad Córdoba Sector 1A",
  "Cancha Múltiple Los Cristales",
  "Unidad Recreativa Los Cristales",
  "Polideportivo Vista Hermosa",
  "Cancha Múltiple La Fortuna",
  "Cancha Múltiple La Playita",
  "Cancha Múltiple Urbanización Aguacatal",
  "Parque Recreativo Villa Del Mar",
  "Coliseo Celestino Mutis",
  "Coliseo Cubierto Bajo Aguacatal",
  "Parque Recreativo Cousaca",
  "Parque Recreativo El Ancla",
  "Polideportivo Las Malvinas",
  "Unidad Recreativa Tory Castro (Crp)",
  "Cancha Múltiple Nacional",
  "Cancha Múltiple Montebello",
  "Polideportivo El Saladito",
  "Cancha De Fútbol Felidia",
  "Cancha De Fútbol Montebello",
  "Cancha De Fútbol 5 San Carlos",
  "Cancha Múltiple Ciudad Modelo",
  "Parque Recreativo Ciudad Modelo",
  "Parque Recreativo El Jardín",
  "Parque Recreativo La Independencia",
  "Parque Tertualiadero 3 Edad San Carlos",
  "Unidad Recreativa Ciudad Modelo (Crp)",
  "Cancha Múltiple El Jardín",
  "Cancha Múltiple El Jardín Autoservicio",
  "Cancha Sintética San Benito",
  "Parque Recreativo 20 De Julio",
  "Parque Recreativo San Benito",
  "Polideportivo El Jardín",
  "Polideportivo Prados De Oriente",
  "Cancha Múltiple La Castilla",
  "Polideportivo Villacarmelo",
  "Cancha Múltiple Las Acacias",
  "Parque Recreativo La India Barrio Santa Elena",
  "Parque Recreativo Barrio Olímpico",
  "Parque Recreativo Colseguros Andes",
  "Parque Recreativo Santa Clara",
  "Polideportivo Cristóbal Colón",
  "Polideportivo Eldorado I",
  "Polideportivo Eldorado II",
  "Polideportivo La 23",
  "Polideportivo San Cristóbal",
  "Polideportivo San Judas Tadeo II",
  "Unidad Recreativa Descubrimiento",
  "Unidad Recreativa El Olímpico (Crp)",
  "Cancha De Baloncesto San Carlos",
  "Cancha De Fútbol Primavera",
  "Cancha Fútbol 11 Villa Del Sur",
  "Cancha Múltiple Del Mico San Carlos",
  "Cancha Múltiple Holguín Garcés",
  "Polideportivo José María Córdoba",
  "Cancha Múltiple Villa Del Sur",
  "Polideportivo La Bombonera",
  "Polideportivo La Esperanza",
  "Polideportivo San Carlos Cancha Santiago Apóstol",
  "Tertuliadero Villa Del Sur",
  "Parque Recreativo Primavera",
  "Parque Recreativo El Recuerdo",
  "Cancha De Fútbol Montebello Mojica II Visa",
  "Cancha Múltiple Comuneros I (El Faro)",
  "Cancha Múltiple Comuneros I (Alfonso Bonilla Naar)",
  "Cancha Sintética 1 Bajo Ciudad Córdoba",
  "Parque Recreativo Y Kiosco Bajos Ciudad Córdoba",
  "Parque Recreativo Canchas Gemelas Mojica II Visa A",
  "Parque Recreativo Comuneros I",
  "Parque Recreativo El Pascualito Comuneros I (Parque Del Muerto)",
  "Parque Recreativo La Bombonera Mojica II",
  "Parque Recreativo Las Palmas",
  "Parque Recreativo Mojica II",
  "Polideportivo Canchas Gemelas Mojica II Visa A",
  "Polideportivo Comuneros I",
  "Unidad Recreativa Laureano Gómez",
  "Cancha Sintética Brisas Del Limonar",
  "Cancha Múltiple El Triángulo Barrio Mariano Ramos",
  "Cancha Sintética República De Israel",
  "Parque Recreativo Antonio Nariño",
  "Parque Recreativo Brisas Del Limonar",
  "Parque Recreativo La Virgen Mariano Ramos",
  "Parque Recreativo República De Israel",
  "Polideportivo Ciudad 2000",
  "Polideportivo Cristo Maestro Barrio Unión De Vivienda Popular",
  "Polideportivo República De Israel",
  "Polideportivo Sport Boys Barrio Mariano Ramos",
  "Polideportivo Unión De Vivienda Popular (Parque De Los Colores)",
  "Unidad Recreativa Las Palmas",
  "Unidad Recreativa Mariano Ramos",
  "Unidad Recreativa Marino Rengifo",
  "Cancha Baloncesto La Colmena El Vallado I",
  "Cancha De Fútbol El Retiro",
  "Cancha Múltiple África El Retiro",
  "Cancha Múltiple Barrio El Retiro",
  "Cancha Múltiple Ciudad Córdoba Sector 3A Y 3B (La Plaga)",
  "Cancha Múltiple Guadalajara El Vallado II",
  "Cancha Múltiple Secon Barrio El Retiro",
  "Cancha Múltiple Suley El Vallado I",
  "Cancha Sintética 2 Bajo Ciudad Córdoba",
  "Parque Recreativo El Pascualito El Vallado II",
  "Parque Recreativo La Amistad El Vallado II",
  "Parque Recreativo Los Bomberos El Vallado II",
  "Polideportivo Barrio El Vallado",
  "Polideportivo Eduardo Vargas (El Vallado)",
  "Unidad Recreativa El Vallado",
]

export async function getItemsDisponibles(seccion: string) {
  try {
    // Primero intentamos obtener los items personalizados
    const { data: customItems, error } = await supabase
      .from("items_disponibles")
      .select("nombre")
      .eq("seccion", seccion)

    if (error) {
      console.error("Error al obtener items personalizados:", error)
      throw error
    }

    const customItemNames = customItems?.map((item) => item.nombre) || []
    const predefinedItems = seccion === "Inmuebles" ? INMUEBLES : MUEBLES

    // Combinar items predefinidos con items personalizados, eliminando duplicados
    const combinedItems = Array.from(new Set([...predefinedItems, ...customItemNames]))

    // Ordenar alfabéticamente
    return combinedItems.sort()
  } catch (error) {
    console.error("Error en getItemsDisponibles:", error)
    // En caso de error, devolver al menos los items predefinidos
    return seccion === "Inmuebles" ? INMUEBLES : MUEBLES
  }
}

